apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: java-quarkus-167842765
  namespace: f2qxde46-tenant
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/hacdev/build_service@sha256:5ef78132b13c14477b57de47d9b6de3c62217c5a6f938c8dece6051f98639817
        name: my-java-quarkus
        resources: {}
status: {}
